repos:
  - repo: local
    hooks:
    - id: black
      name: black
      entry: black src --config pyproject.toml
      language: python
      types: [python]
      additional_dependencies: [black==25.1.0]


    - id: isort
      name: isort
      entry: isort src
      language: python
      types: [python] 
      additional_dependencies: [isort==6.0.1]

    - id: pylint
      name: pylint
      entry: pylint src
      exclude: ^tests/
      language: python
      types: [python]
      additional_dependencies: [pylint==3.3.6]