[tool.black]
exclude="""
    venv/
    tests/
"""

[tool.isort]
profile = "black"
lines_after_imports = 2
include_trailing_comma = true
skip = ["__init__.py"]

[tool.pytest.ini_options]
pythonpath = "src"
asyncio_default_fixture_loop_scope = "function"